site_name: F1 Telemetry
copyright: Copyright &copy; 2022 Idar Bergli
repo_name: idarb-oss/F1Telemetry-dotnet
repo_url: https://github.com/idarb-oss/F1Telemetry-dotnet

nav:
  - Home: 'README.md'

theme:
  name: material
  palette:
    #scheme: slate
    primary: teal
    accent: 'deep orange'
  font:
    code: Roboto Mono
  language: en
  logo: img/f1.svg
  favicon: img/f1.svg
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - header.autohide

plugins:
  - search:
      prebuild_index: true
  - git-revision-date:

extra:
  version:
    provider: mike
#  alternate:
#    - name: English
#      link: /en/
#      lang: en

markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
